#!/bin/bash

echo "L-LITE OS installer"
sleep 2s
sudo su
clear
#########################


#REPOSITORIOS
cp pkg/sources.list /etc/apt/sources.list
apt update


#SET NECESARIO PARA COMPILAR PAQUETES SHAVAL
apt install  linux-headers-$(uname -r) build-essential checkinstall make automake cmake autoconf git git-core


#PAQUETES
apt install xfce-goodies plank neofetch compton wget mpv

##temas/iconos
apt -t ascii-backports install adapta-gtk-theme papirus-icon-theme

##libreoffice-suite
apt install libreoffice libreoffice-gtk2 libreoffice-l10-es

##tipografia-winbugs
apt install ttf-mscorefonts-installer

##vscode
wget https://az764295.vo.msecnd.net/stable/b37e54c98e1a74ba89e03073e5a3761284e3ffb0/code_1.38.1-1568209190_amd64.deb
apt install ./code_1.38.1-1568209190_amd64.deb


#ENTORNO
##inicio
tar -zxvf pkg/autostart.tar.gz
cp pkg/autostart /$HOME/.config/

##paneles-temas
tar -zxvf pkg/xfceconfig.tar.gz
cp pkg/xfceconfig/xfce-panel.xml /$HOME/.config/xfce4/xfconf/xfce-perchannel-xml/
cp pkg/xfceconfig/xsettings.xml /$HOME/.config/xfce4/xfconf/xfce-perchannel-xml/

##wallpaper
xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitor0/workspace0/last-image -s "pkg/wallpapers/default.jpg"


#SLIM
apt install slim
tar -zxvf pkg/liteslimtheme.tar.gz
cp pkg/liteslim /usr/share/slim/themes
cp pkg/slim.conf /etc/slim.conf


#PLYMOUTH
apt purge wicd
cp pkg/interfaces /etc/network/interfaces
apt install  network-manager-gnome
wget http://ftp.us.debian.org/debian/pool/main/p/plymouth/plymouth_0.9.0-9_amd64.deb
apt install ./plymouth_0.9.0-9_amd64.deb
tar -zxvf plymouthllite.tar.gz
cp pkg/futureprototype /usr/share/plymouth/themes/
plymouth-set-default-theme -R futureprototype
cp pkg/grub /etc/default/grub
update-grub
update-grub2

###FINALIZAR###
echo "El sistema se reiniara para concretar la instalacion...."
sleep 3s 
echo "Gracias por instalar L-LITEOS"
sleep 1s
reboot
